version: "3.7"

services:
  database:
    image: postgres
    container_name: database_pratica02
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=pratica02
      - POSTGRES_DB=pratica02_Gustavo
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: pratica02
    ports: 
      - 3333:3333
    volumes: 
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local